### PR TITLE
optimising bash scripts.

### PR DESCRIPTION
**Pull request by codenio**
we could dynamically feed those streams into diff instead of storing it in files.

### CODE REVIEW

**Review by zjj2wry — APPROVED** [review]
lgtm

**Comment by zjj2wry** [comment]
@aananthraj thank you

**Comment by xiangpengzhao** [comment]
@aananthraj awesome! :+1: :100:

**Comment by codenio** [comment]
thanks @zjj2wry 👍  and @xiangpengzhao 😊 , for the support and the feedback.

FYI, new features like,
  * diff on upgrade 
  * diff on rollback 
  * diff between revisions

have been made available as a pull request in [helm-diff](https://github.com/databus23/helm-diff/pull/22) go plugin, and i am waiting for it to be merged.

It would be helpful, if you people could give your opinion/suggestion on those features.

Thanks

**Pull request merged**
